-- AlterTable
ALTER TABLE "Candidate" ALTER COLUMN "firstName" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "lastName" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "Education" ALTER COLUMN "title" SET DATA TYPE VARCHAR(250);

-- AlterTable
ALTER TABLE "Resume" ALTER COLUMN "filePath" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "fileType" SET DATA TYPE VARCHAR(50);
